# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-10 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0004_trousers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trousers',
            new_name='Trouser',
        ),
    ]
