# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-10 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0006_jeans'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jeans',
            new_name='Jean',
        ),
    ]
